// Type definitions - these will be generated by the plugin
export interface RPCRoutes {
  // Generated types will be merged here
}

export type RPCClient = {
  [K in keyof RPCRoutes]: {
    [M in keyof RPCRoutes[K]]: (
      input?: Omit<RPCRoutes[K][M], 'response'>
    ) => Promise<RPCRoutes[K][M]['response']>;
  };
};